// <auto-generated />
using System;
using Gestion_Dépenses.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion_Dépenses.Migrations
{
    [DbContext(typeof(DepenseDbContext))]
    [Migration("20250124220947_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Gestion_Dépenses.Models.Depense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Nature")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Depenses");

                    b.HasDiscriminator<int>("Nature");
                });

            modelBuilder.Entity("Gestion_Dépenses.Models.Deplacement", b =>
                {
                    b.HasBaseType("Gestion_Dépenses.Models.Depense");

                    b.Property<int>("Distance")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Gestion_Dépenses.Models.Restaurant", b =>
                {
                    b.HasBaseType("Gestion_Dépenses.Models.Depense");

                    b.Property<int>("NombreInvites")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(1);
                });
#pragma warning restore 612, 618
        }
    }
}
